allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
minimumReleaseAgeExclude:
  - '@vitest/coverage-v8@4.1.7'
  - '@vitest/pretty-format@4.1.7'
  - '@vitest/utils@4.1.7'
overrides:
  tmp: ^0.2.4
